name: feature-pipeline
on:  [push]
jobs:
  feature-pipeline:
    uses: azharmd-dev/workflows/.github/workflows/feature-nodejs-pipeline.yaml@main
    with:
      project: robomart
      component: catalogue
      environment: dev

