name: feature-pipeline
on:  [push]
jobs:
  feature-nodejs-pipeline:
    runs-on: [self-hosted, Linux, X64] 
    uses: azharmd-dev/workflows/.github/workflows/feature-nodejs-pipeline.yaml@main
    with:
      project: robomart
      component: catalogue
      environment: dev

