name: feature-d-pipeline
on:  [push]
jobs:
  feature-nodejs-pipeline:
    uses: azharmd-dev/workflows/.github/workflows/feature-nodejs-pipeline.yaml@main
    with:
      project: robomart
      component: catalogue
      environment: dev

